### ISSUE TITLE
bug in log.c+66

### ISSUE THREAD

**Issue by LiaoXiaoQiang** [loadingvx/clib#13]
when running log.usage.c, I found that if I put a minute which is smaller than local time minute, the program will rename the output log file the first time it reach the follow condition:
![image](https://cloud.githubusercontent.com/assets/12265349/7650503/a263be8a-fb29-11e4-981e-1b7816ef4917.png)
for that the setting.cnt is initialized with 0, then no output will generate.
I think there should be a Non-zero judgement.

**Comment by loadingvx** [comment]
The condition "setting.cnt % precheck == 0 " was designed to reduce checking for logrotate, so that, it will not try to run logrotate each time you call info/debug/...
It will be great if you add a file-size testing inner logrotate-function to avoid empty log file generation.

Would you make a patch for this ?
When time pasted, a rotate need to be proformed but we do don't want any empty log-file.

**Comment by loadingvx** [comment]
Fixed by :  https://github.com/loadingvx/clib/pull/15
